/* oracle_diff — run the same guest function through the interpreter and the
 * recompiled C, and report where they disagree.
 *
 * This is the tier-1 oracle from psprecomp's docs/ORACLE.md, pointed at
 * Armored Core. The two sides share their decoder, CPU state, memory model and
 * semantic helpers; the only thing that differs is that one sequences
 * instructions itself and the other runs emitted control flow. So a divergence
 * localises to the emitter or to the interpreter's sequencing, and nowhere
 * else. That narrowing is the entire value.
 *
 * Method, per function: build a deterministic starting state, snapshot it, run
 * one side, capture the result, restore, run the other, compare.
 *
 * Firmware calls used to be excluded: the recompiled stub called psp_hle_call()
 * while the interpreter ran the unlinked `jr $ra` still sitting in the module,
 * so the two disagreed at every import by construction. The interpreter now
 * routes thunk hits into HLE as well (psp_interp_set_imports), and both sides
 * cross the boundary identically.
 *
 * Two things are still excluded:
 *
 *   Guest re-entry from HLE. A few handlers call back into guest code — a
 *   thread entry point, a registered callback — through psp_dispatch(), which
 *   only knows about *recompiled* functions. On the interpreter's side of the
 *   comparison that would quietly run recompiled code, so the run is no longer
 *   independent and the result proves nothing. Detected by watching the
 *   dispatch counter and skipped.
 *
 *   Traps. Either side may hit an unimplemented instruction. A trap on both
 *   sides at the same place is agreement, not a finding.
 */

#include "interp.h"
#include "decode.h"
#include "container.h"

#include "psprecomp/cpu.h"
#include "psprecomp/mem.h"
#include "psprecomp/dispatch.h"
#include "psprecomp/hle.h"

#include <setjmp.h>
#include <signal.h>
#include <unistd.h>
#include <sys/time.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Generated by allegrexrecomp; declared here so the harness does not depend on
 * a particular emit prefix being on the include path. */
void psp_recomp_register(void);

#define STACK_TOP  (PSP_RAM_BASE + PSP_RAM_SIZE - 0x1000)
#define RA_DONE    0x0DEAD000u

/* ---- trap capture ---------------------------------------------------------
 *
 * The recompiled path reports an untranslatable instruction by calling
 * psp_unimplemented(), which a real host would make fatal. Here it has to be
 * survivable: the harness wants to note "this side trapped" and move on to the
 * next function, not take the process down. longjmp is the only way back out
 * of generated code, which has no error return of its own. */

static sigjmp_buf g_trap;
static int        g_trapped;      /* 1 = trap, 2 = watchdog timeout */
static uint32_t   g_trap_addr;
static const char *g_trap_what;

void psp_unimplemented(uint32_t addr, const char *what) {
    g_trapped = 1; g_trap_addr = addr; g_trap_what = what;
    siglongjmp(g_trap, 1);
}

void psp_syscall(uint32_t id) {
    g_trapped = 1; g_trap_addr = id; g_trap_what = "syscall";
    siglongjmp(g_trap, 1);
}

/* The interpreter stops itself at an instruction budget. The recompiled side
 * has no such control: it is ordinary C, and a function that loops forever
 * loops forever. That is not hypothetical — the harness hung on it — and it is
 * also interesting, because the interpreter having *returned* from the same
 * function on the same input means the two disagree about termination.
 *
 * So: a wall-clock watchdog. Jumping out of a signal handler is not something
 * to do in shipped code, but this is a development harness and the alternative
 * is no result at all. */
/* psp_dispatch's default miss handler aborts. That is right for a real host and
 * wrong here: the seeded argument registers mean an HLE handler can be handed a
 * garbage function pointer and try to dispatch on it, which is a property of
 * the test inputs rather than a defect. Record and continue; the caller treats
 * any dispatch activity during an interpreter run as grounds to skip. */
static uint64_t g_miss_count;

/* Phase markers for diagnosing a hang. write(2) rather than stdio: this has to
 * work when the question is whether stdio itself is wedged. */
static int g_phase_trace;
static void phase(const char *tag) {
    if (g_phase_trace) { write(2, "[", 1); write(2, tag, strlen(tag)); write(2, "]\n", 2); }
}

static void note_miss(uint32_t addr) {
    (void)addr;
    g_miss_count++;
}

static void watchdog(int sig) {
    (void)sig;
    g_trapped = 2;
    siglongjmp(g_trap, 1);
}

/* Recompiled guest code is ordinary C running on the host stack, and every
 * guest call is a real call. A deep or mutually recursive guest chain -- easy
 * to reach from seeded argument registers -- overflows that stack and the
 * process dies with SIGSEGV, taking the whole corpus run with it. Both full
 * runs stopped at the same function for this reason.
 *
 * Catching it needs an alternate signal stack, because by the time the fault
 * arrives the normal one has no room left to run a handler on. Treated as a
 * skip: it says the harness cannot evaluate this function, not that the two
 * sides disagree. */
static void faulted(int sig) {
    (void)sig;
    g_trapped = 3;
    siglongjmp(g_trap, 1);
}

static void install_fault_handler(void) {
    static char altstack[SIGSTKSZ < 65536 ? 65536 : SIGSTKSZ];
    stack_t ss = { .ss_sp = altstack, .ss_size = sizeof altstack, .ss_flags = 0 };
    sigaltstack(&ss, NULL);

    struct sigaction sa;
    memset(&sa, 0, sizeof sa);
    sa.sa_handler = faulted;
    sa.sa_flags   = SA_ONSTACK | SA_NODEFER;
    sigemptyset(&sa.sa_mask);
    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGBUS,  &sa, NULL);
}

/* alarm(2) was the first attempt and made a 400-function run take longer than
 * ten minutes: once firmware calls started doing real work, far more functions
 * ran long enough to reach the timeout, and each one then cost a full two
 * seconds of wall clock. setitimer gives sub-second granularity. A function
 * the interpreter finished in under 200k instructions has no business taking
 * this long as native code. */
#define WATCHDOG_USEC  200000

static void watchdog_arm(void) {
    struct itimerval t = {{0, 0}, {0, WATCHDOG_USEC}};
    setitimer(ITIMER_REAL, &t, NULL);
}

static void watchdog_disarm(void) {
    struct itimerval t = {{0, 0}, {0, 0}};
    setitimer(ITIMER_REAL, &t, NULL);
}

/* ---- state snapshots ------------------------------------------------------
 *
 * Comparing the register file alone would miss the whole class of bugs where a
 * function computes the right answer into the wrong address, so memory is
 * compared too.
 *
 * Not *all* memory, though: copying 32 MB of RAM three times per function made
 * the harness slower than the thing it is testing. Two regions actually carry
 * the state a function under test can reach from a clean start:
 *
 *   the stack window   — a 1 MB span below the initial $sp
 *   the module image   — code and the data segment, mapped at the link address
 *
 * The seeded argument registers are deliberately small (0..0x3FFF), and the
 * module maps at 0, so a stray pointer write lands inside the module image and
 * is caught. What this does NOT cover is a write to arbitrary high RAM, which
 * from a zeroed start requires an address the function invented rather than
 * received. Worth revisiting if a divergence is ever suspected and not found. */

/* Full RAM. A narrower window was tried and was wrong: functions here reach
 * memory through globals in the data segment, so a write can land anywhere in
 * RAM. Restoring only a stack window left those writes visible to the second
 * run, which manufactured divergences that looked exactly like codegen bugs.
 * Correctness first; this costs about 30 ms per function. */
#define STACK_WIN_LEN  PSP_RAM_SIZE
#define STACK_WIN_OFF  0u

typedef struct {
    psp_cpu_state cpu;
    uint8_t      *stack;
    uint8_t      *module;
    uint64_t      bad_access;
} snapshot;

static uint8_t *g_module_host;
static uint32_t g_module_lo, g_module_size;

static void snap_alloc(snapshot *s) {
    s->stack  = malloc(STACK_WIN_LEN);
    s->module = malloc(g_module_size);
    if (!s->stack || !s->module) { fprintf(stderr, "out of memory\n"); exit(1); }
}

static void snap_take(snapshot *s) {
    s->cpu = psp_cpu;
    memcpy(s->stack,  psp_mem.ram + STACK_WIN_OFF, STACK_WIN_LEN);
    memcpy(s->module, g_module_host, g_module_size);
    s->bad_access = psp_mem_bad_access;
}

static void snap_restore(const snapshot *s) {
    psp_cpu = s->cpu;
    memcpy(psp_mem.ram + STACK_WIN_OFF, s->stack,  STACK_WIN_LEN);
    memcpy(g_module_host, s->module, g_module_size);
    psp_mem_bad_access = s->bad_access;
}

/* ---- deterministic starting state -----------------------------------------
 *
 * Argument registers get pseudo-random values so the comparison exercises real
 * data paths rather than the all-zero case, which hides sign handling and
 * masks whole branches. The generator is a plain LCG seeded from the function
 * address: identical every run, so a divergence can be reproduced exactly.
 *
 * The values are kept small and non-negative. Wild pointers would send both
 * sides into unmapped memory, where they agree trivially (reads return 0) and
 * the test proves nothing. */

static void seed_state(uint32_t addr) {
    memset(&psp_cpu, 0, sizeof psp_cpu);
    uint32_t x = addr * 1103515245u + 12345u;
    for (int i = 4; i <= 7; i++) {          /* $a0..$a3 */
        x = x * 1103515245u + 12345u;
        psp_cpu.r[i] = (x >> 16) & 0x3FFF;
    }
    for (int i = 8; i <= 15; i++) {         /* $t0..$t7 */
        x = x * 1103515245u + 12345u;
        psp_cpu.r[i] = (x >> 16) & 0x3FFF;
    }
    psp_cpu.r[PSP_REG_SP] = STACK_TOP;
    psp_cpu.r[PSP_RA_INDEX] = RA_DONE;
}

/* ---- comparison ----------------------------------------------------------- */

/* Callee-saved registers plus the return values are what a caller can observe.
 * $t0-$t9 and $a0-$a3 are caller-saved: the two sides are entitled to leave
 * different garbage there, and comparing them produces noise, not findings. */
static int reg_is_observable(int i) {
    if (i == PSP_REG_V0 || i == PSP_REG_V1) return 1;         /* returns */
    if (i >= PSP_REG_S0 && i <= PSP_REG_S7) return 1;         /* callee-saved */
    if (i == PSP_REG_SP || i == PSP_REG_FP || i == PSP_REG_GP) return 1;
    return 0;
}

static int compare(const snapshot *a, const snapshot *b, uint32_t addr, int verbose) {
    int diffs = 0;

    for (int i = 0; i < PSP_NUM_GPR; i++) {
        if (!reg_is_observable(i)) continue;
        if (a->cpu.r[i] != b->cpu.r[i]) {
            if (verbose || diffs < 4)
                printf("  %08X  $%-4s interp=%08X recomp=%08X\n",
                       addr, psp_reg_names[i], a->cpu.r[i], b->cpu.r[i]);
            diffs++;
        }
    }
    if (a->cpu.hi != b->cpu.hi) { printf("  %08X  hi   interp=%08X recomp=%08X\n",
                                         addr, a->cpu.hi, b->cpu.hi); diffs++; }
    if (a->cpu.lo != b->cpu.lo) { printf("  %08X  lo   interp=%08X recomp=%08X\n",
                                         addr, a->cpu.lo, b->cpu.lo); diffs++; }

    if (memcmp(a->stack, b->stack, STACK_WIN_LEN) != 0) {
        for (uint32_t o = 0; o < STACK_WIN_LEN; o += 4) {
            if (memcmp(a->stack + o, b->stack + o, 4) == 0) continue;
            printf("  %08X  stack[%08X] interp=%02X%02X%02X%02X recomp=%02X%02X%02X%02X\n",
                   addr, PSP_RAM_BASE + STACK_WIN_OFF + o,
                   a->stack[o+3], a->stack[o+2], a->stack[o+1], a->stack[o],
                   b->stack[o+3], b->stack[o+2], b->stack[o+1], b->stack[o]);
            diffs++;
            break;
        }
    }
    if (memcmp(a->module, b->module, g_module_size) != 0) {
        /* Report where, not just that. "module image differs" is unactionable:
         * the offset says whether this is a data-segment global, a write
         * through a wild pointer, or code being overwritten. */
        uint32_t first = 0;
        int shown = 0;
        for (uint32_t o = 0; o + 4 <= g_module_size; o += 4) {
            if (memcmp(a->module + o, b->module + o, 4) == 0) continue;
            first = o;
            printf("  %08X  module[%08X] interp=%02X%02X%02X%02X recomp=%02X%02X%02X%02X\n",
                   addr, g_module_lo + o,
                   a->module[o+3], a->module[o+2], a->module[o+1], a->module[o],
                   b->module[o+3], b->module[o+2], b->module[o+1], b->module[o]);
            shown = 1;
            break;
        }
        if (!shown) printf("  %08X  module image differs\n", addr);
        (void)first;
        diffs++;
    }
    return diffs;
}

/* ---- one function --------------------------------------------------------- */

typedef enum { R_MATCH, R_DIFF, R_SKIP_IMPORT, R_SKIP_NOFN, R_SKIP_TRAP, R_HANG, R_SKIP_UNBALANCED, R_SKIP_REENTRY, R_HANG_INTERP, R_FAULT, R_DIFF_MISS } result;

static uint32_t g_stub_lo, g_stub_hi;

static snapshot g_pristine;   /* the loaded module, before anything ran */

static result check_one(uint32_t addr, snapshot *base, snapshot *si, snapshot *sr,
                        int verbose) {
    psp_fn_t fn = psp_lookup(addr);
    if (!fn) return R_SKIP_NOFN;

    /* Start every function from the freshly-loaded image, not from whatever the
     * previous one left behind. Without this the harness is order-dependent:
     * each function inherits the last one's writes, memory degrades as the run
     * goes on, and later functions start reading code as data. That shows up as
     * registers holding MIPS instruction words -- which looks exactly like a
     * codegen bug and is not one. */
    snap_restore(&g_pristine);

    seed_state(addr);
    snap_take(base);

    /* --- interpreter --- */
    psp_interp it;
    psp_interp_init(&it, addr, RA_DONE, 200000);

    /* Thunk hits now go through HLE inside psp_interp_step, so the stub region
     * is no longer a stopping condition. What still is: an HLE handler calling
     * psp_dispatch() to re-enter guest code, which runs the *recompiled*
     * version and destroys this side's independence. The dispatch counter is
     * how that shows up afterwards.
     *
     * Afterwards is not always soon enough. The interpreter bounds itself with
     * an instruction budget, but that budget does not cover time spent inside
     * an HLE handler — and a handler that re-enters guest code can land in a
     * recompiled function that never returns. The interpreter then never gets
     * its own loop back and the budget is never consulted. So the wall-clock
     * watchdog has to cover this side too, not just the recompiled run. */
    phase("interp-start");
    const uint64_t dispatch_before = psp_dispatch_calls();
    const uint64_t miss_before     = g_miss_count;
    g_trapped = 0;
    if (sigsetjmp(g_trap, 1) == 0) {
        watchdog_arm();
        psp_interp_run(&it);
        watchdog_disarm();
    } else {
        watchdog_disarm();
    }
    phase("interp-done");
    if (g_trapped == 2) return R_HANG_INTERP;
    if (g_trapped == 3) return R_FAULT;
    if (g_trapped)      return R_SKIP_TRAP;
    if (psp_dispatch_calls() != dispatch_before || g_miss_count != miss_before)
        return R_SKIP_REENTRY;
    if (it.status != I_OK_RETURN)                return R_SKIP_TRAP;

    /* Stack balance is the test for "was this address really callable?".
     *
     * Discovery splits on any address something points at, so a `function` can
     * begin in the middle of a real one — past the prologue that allocated the
     * frame. Entering there, the epilogue's `lw $ra, N($sp)` reads a slot no
     * prologue ever wrote, and the interpreter jumps to whatever garbage that
     * yields and runs on until it happens to reach the sentinel. The recompiled
     * side just returns off the end of its C body. The two then disagree about
     * everything, and none of it is a codegen bug.
     *
     * A well-formed function leaves $sp exactly as it found it. Anything else
     * was not independently callable, so the comparison is meaningless rather
     * than failing. (psprecomp makes the same check for the same reason —
     * see PSP_SP_CHECK in the generated code.) */
    if (psp_cpu.r[PSP_REG_SP] != STACK_TOP) return R_SKIP_UNBALANCED;

    phase("snap-si");
    snap_take(si);

    phase("recomp-start");
    /* --- recompiled --- */
    const uint64_t miss_after_interp = g_miss_count;
    snap_restore(base);
    g_trapped = 0;
    if (sigsetjmp(g_trap, 1) == 0) {
        watchdog_arm();
        fn();
        watchdog_disarm();
    } else {
        watchdog_disarm();
    }
    phase("recomp-done");
    if (g_trapped == 2) return R_HANG;
    if (g_trapped == 3) return R_FAULT;
    if (g_trapped)      return R_SKIP_TRAP;
    phase("snap-sr");
    snap_take(sr);

    const int diffs = compare(si, sr, addr, verbose);
    if (!diffs) return R_MATCH;

    /* A dispatch miss during the recompiled run explains a divergence without
     * implicating the emitter. The interpreter follows an indirect jump to
     * whatever it computes; the recompiled side hands the same address to
     * psp_dispatch(), which does nothing when discovery never registered it.
     * The two then legitimately do different work, and the defect is in
     * discovery's coverage, not in the code that was generated. Worth counting
     * separately -- the fix is a different one. */
    if (g_miss_count != miss_after_interp) {
        if (verbose)
            printf("  %08X  (dispatch miss during the recompiled run: discovery gap)\n", addr);
        return R_DIFF_MISS;
    }
    return R_DIFF;
}

/* -------------------------------------------------------------------------- */

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr,
            "oracle_diff <module.elf> [--limit N] [--from ADDR] [--verbose]\n"
            "\n"
            "Runs each discovered function through the interpreter and the\n"
            "recompiled C and reports disagreements.\n");
        return 2;
    }
    const char *path = argv[1];
    long limit = 2000;
    uint32_t only = 0; int have_only = 0;
    const char *funcs_path = NULL;
    int verbose = 0;
    for (int i = 2; i < argc; i++) {
        if (!strcmp(argv[i], "--limit") && i + 1 < argc) limit = strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--from") && i + 1 < argc) { only = (uint32_t)strtoul(argv[++i], NULL, 0); have_only = 1; }
        else if (!strcmp(argv[i], "--verbose")) verbose = 1;
        else if (!strcmp(argv[i], "--phase")) g_phase_trace = 1;
        else if (!strcmp(argv[i], "--funcs") && i + 1 < argc) funcs_path = argv[++i];
        else { fprintf(stderr, "unknown option %s\n", argv[i]); return 2; }
    }

    psp_blob b;
    if (psp_blob_read(path, &b) != 0) { fprintf(stderr, "cannot read %s\n", path); return 1; }
    elf_info e;
    if (elf_parse(b.data, b.size, &e) != 0) { fprintf(stderr, "not an ELF/PRX\n"); return 1; }
    if (psp_mem_init() != 0) { fprintf(stderr, "no guest memory\n"); return 1; }

    uint32_t lo = UINT32_MAX, hi = 0;
    for (int i = 0; i < e.nsegments; i++) {
        if (e.seg[i].addr < lo) lo = e.seg[i].addr;
        if (e.seg[i].addr + e.seg[i].memsz > hi) hi = e.seg[i].addr + e.seg[i].memsz;
    }
    psp_mem_map_module(lo, hi - lo);
    for (int i = 0; i < e.nsegments; i++)
        if (e.seg[i].filesz)
            psp_mem_write_block(e.seg[i].addr, b.data + e.seg[i].offset, e.seg[i].filesz);

    g_module_lo   = lo;
    g_module_size = hi - lo;
    g_module_host = psp_mem_ptr(lo, 1);
    if (!g_module_host) { fprintf(stderr, "module mapping failed\n"); return 1; }

    g_stub_lo = e.stub_addr;
    g_stub_hi = e.stub_addr + e.stub_size;

    signal(SIGALRM, watchdog);
    install_fault_handler();
    psp_set_miss_handler(note_miss);
    psp_recomp_register();
    psp_hle_init();
    /* Millions of firmware calls follow, and the watchdog longjmps out of a
     * signal handler -- an fprintf interrupted mid-call would leave stdio's
     * lock held and deadlock the next one. See psp_hle_set_quiet in hle.c. */
    psp_hle_set_quiet(1);

    /* Give the interpreter the same firmware boundary the recompiled stubs
     * have. Without this every function reaching an import is uncomparable. */
    int nimp = 0;
    psp_module_info mi;
    if (e.modinfo_size && psp_modinfo_parse(b.data, b.size, e.modinfo_offset, &mi) == 0) {
        const uint32_t bias = e.nsegments ? e.seg[0].offset - e.seg[0].addr : 0;
        int n = psp_collect_imports(b.data, b.size, &mi, bias, NULL, 0);
        if (n > 0) {
            psp_import_entry *imp = malloc((size_t)n * sizeof *imp);
            psp_interp_import *tbl = malloc((size_t)n * sizeof *tbl);
            if (imp && tbl) {
                n = psp_collect_imports(b.data, b.size, &mi, bias, imp, n);
                for (int i = 0; i < n; i++) { tbl[i].addr = imp[i].addr; tbl[i].nid = imp[i].nid; }
                nimp = psp_interp_set_imports(tbl, n);
            }
            free(imp);
        }
    }

    snapshot base, si, sr;
    snap_alloc(&base); snap_alloc(&si); snap_alloc(&sr);
    snap_alloc(&g_pristine);
    snap_take(&g_pristine);

    printf("module:   %s\n", path);
    printf("mapped:   0x%08X + %u bytes\n", lo, g_module_size);
    printf("stubs:    0x%08X..0x%08X (%u bytes, %d routed to HLE)\n",
           g_stub_lo, g_stub_hi, e.stub_size, nimp);
    printf("text:     0x%08X + %u bytes\n", e.text_addr, e.text_size);
    printf("---\n");

    long attempted = 0, match = 0, diff = 0;
    long skip_import = 0, skip_trap = 0, skip_nofn = 0, hang = 0, skip_unbal = 0, skip_reentry = 0, hang_interp = 0, faults = 0, diff_miss = 0, skip_stub = 0;

    /* Walk .text on instruction boundaries and test whatever the dispatch
     * table knows about. Using the dispatch table as the work-list means the
     * harness tests exactly the set the emitter claims to have translated.
     *
     * `limit` bounds *attempts*, not successful comparisons. Bounding successes
     * instead makes the loop unbounded whenever most functions are skipped —
     * which is the common case here, since anything touching an import is
     * excluded — and the harness then grinds through all 26,487 functions
     * running each one to its instruction budget first. */
    const uint32_t text_lo = e.text_addr, text_hi = e.text_addr + e.text_size;

    /* The work-list.
     *
     * Walking .text and testing whatever psp_lookup resolves is wrong: the
     * dispatch table holds interior labels as well as function entries -- for
     * this module, 32,068 of the former against 26,487 of the latter. A label
     * sits past the prologue that set up the frame, so entering there is not a
     * call and the comparison is meaningless. The $sp-balance check catches
     * most of them after the fact, but at the cost of running each one first.
     *
     * With --funcs, the entry list from `allegrexrecomp funcs --list` is used
     * instead, so only real entries are attempted. */
    uint32_t *worklist = NULL;
    long nwork = 0;
    if (funcs_path) {
        FILE *lf = fopen(funcs_path, "r");
        if (!lf) { fprintf(stderr, "cannot read %s\n", funcs_path); return 1; }
        long cap = 4096;
        worklist = malloc((size_t)cap * sizeof *worklist);
        char line[256];
        while (worklist && fgets(line, sizeof line, lf)) {
            unsigned a;
            if (sscanf(line, " 0x%x", &a) != 1) continue;
            if (nwork == cap) {
                cap *= 2;
                uint32_t *bigger = realloc(worklist, (size_t)cap * sizeof *worklist);
                if (!bigger) break;
                worklist = bigger;
            }
            worklist[nwork++] = a;
        }
        fclose(lf);
        printf("worklist: %ld function entries from %s\n", nwork, funcs_path);
    }

    for (long wi = 0; ; wi++) {
        uint32_t a;
        if (have_only)      { if (wi) break; a = only; }
        else if (worklist)  { if (wi >= nwork || attempted >= limit) break; a = worklist[wi]; }
        else {
            a = text_lo + (uint32_t)wi * 4;
            if (a >= text_hi || attempted >= limit) break;
        }
        if (!psp_lookup(a)) continue;
        /* Import thunks are in .text and land in the discovered function list,
         * but they are not functions -- they are the firmware boundary. The
         * interpreter intercepts them into HLE and the recompiled side has a
         * generated stub; comparing the two as if they were guest code
         * measures nothing. */
        if (a >= g_stub_lo && a < g_stub_hi) { skip_stub++; continue; }
        attempted++;
        switch (check_one(a, &base, &si, &sr, verbose)) {
        case R_MATCH:        match++; break;
        case R_DIFF:         diff++;  break;
        case R_SKIP_IMPORT:  skip_import++; break;
        case R_SKIP_TRAP:    skip_trap++;   break;
        case R_SKIP_NOFN:    skip_nofn++;   break;
        case R_HANG:         hang++;        break;
        case R_SKIP_UNBALANCED: skip_unbal++; break;
        case R_SKIP_REENTRY: skip_reentry++; break;
        case R_HANG_INTERP:  hang_interp++;  break;
        case R_FAULT:        faults++;       break;
        case R_DIFF_MISS:    diff_miss++;    break;
        }
        if ((attempted % 200) == 0) {
            printf("... %ld attempted, %ld compared\n", attempted, match + diff);
            fflush(stdout);
        }
    }

    printf("---\n");
    printf("attempted: %ld functions\n", attempted);
    printf("compared:  %ld\n", match + diff + diff_miss);
    printf("  match:  %ld\n", match);
    printf("  differ: %ld\n", diff);
    printf("  differ (dispatch miss -- discovery gap, not codegen): %ld\n", diff_miss);
    printf("skipped:\n");
    printf("  HLE re-entry:    %ld  (handler called back into guest code)\n", skip_reentry);
    printf("  trapped:         %ld  (unimplemented instruction on one side)\n", skip_trap);
    printf("  recomp hung:     %ld  (interpreter returned; recompiled C did not)\n", hang);
    printf("  interp hung:     %ld  (watchdog fired inside the interpreter run)\n", hang_interp);
    printf("  unbalanced $sp:  %ld  (entry was not independently callable)\n", skip_unbal);
    printf("  host fault:      %ld  (SIGSEGV/SIGBUS, usually host stack exhaustion)\n", faults);
    printf("  import thunk:    %ld  (firmware boundary, not guest code)\n", skip_stub);

    psp_mem_free();
    psp_blob_free(&b);
    return diff ? 1 : 0;
}
